FROM ubuntu@sha256:019e8eb29a85e74d64925745884f2ec79aa27e3feab36353d24656f4d6b89467

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
       bison build-essential ca-certificates curl file flex \
       g++-multilib gcc-multilib mingw-w64 xvfb xauth jq libdigest-sha-perl \
       libfreetype-dev libgnutls28-dev libx11-dev libxcursor-dev \
       libxext-dev libxfixes-dev libxi-dev libxrandr-dev libxrender-dev \
       patch pkg-config python3 tar \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
